### ISSUE TITLE
Wormote

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#1017]
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/12d78d36-62b1-4c99-88dc-23eba56ae504)

**Comment by ChespinCraft** [comment]
![Image](https://github.com/untamed-team/project-untamed/assets/70040639/b4a10b9a-9ccc-4e0f-be76-de80095f6fa4)
![Image](https://github.com/untamed-team/project-untamed/assets/70040639/a0d1e3ea-ce34-41e6-b7ca-18423e4880cc)
