### ISSUE TITLE
Alma (Ghost Gym)

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#1269]
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/e4ccfbee-5864-4044-a213-4e9686f7a129)

**Comment by ChespinCraft** [comment]
Could use a color swap to match updated sprites


![Image](https://github.com/untamed-team/project-untamed/assets/70040639/a517d634-305e-4092-908d-387ace1e02be)
