### ISSUE TITLE
trainer backsprites 

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#130]
currently:
![POKEMONTRAINER_Leaf_back](https://user-images.githubusercontent.com/73248181/187402665-5f15cb11-093b-461e-af7c-2a3deb87c5f1.png)
![POKEMONTRAINER_Red_back](https://user-images.githubusercontent.com/73248181/187402669-3ab57942-eebd-4ab2-a753-f0fa84bdaa6a.png)

**Comment by Gardenette** [comment]
We need ball throw for player male and female, and we need the sprites for the player pointing as well when sending follower into battle

**Comment by Gardenette** [comment]
Being worked on by Spork
