### ISSUE TITLE
ThaliaVS

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#1309]
Rusty Rust [Jan 10 at 12:28 PM](https://trello.com/c/5KLtZoqp/13-thaliavs#comment-659ed3b030793a4d0e4378e1)
I think its done but open for fixing

![Image](https://github.com/untamed-team/project-untamed/assets/106409863/84556365-9db8-4f00-8495-8b193505b827)

**Comment by ChespinCraft** [comment]
![Image](https://github.com/untamed-team/project-untamed/assets/70040639/6ee060e7-f114-4de3-9ad3-0b5ca948288e)
