### ISSUE TITLE
Remake jukebox

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#150]
Please let's just scrap the radio. I hate it :(

**Comment by stygmaskyzoo** [comment]
why dont just scrap pokegear?

**Comment by Gardenette** [comment]
Scrapped pokegear. The jukebox should be a thing though. Just low priority

**Comment by Gardenette** [comment]
Will likely be part of phone

**Comment by KalojaGod** [comment]
https://discord.com/channels/969006224039370794/1074140652025167953/1074140652025167953

maybe?

**Comment by KalojaGod** [comment]
Keep out of overworld. Keep jukebox to camp.

**Comment by Gardenette** [comment]
Duplicate of task in camp issue
