### ISSUE TITLE
Background behind ceiba in intro needs to be an actual background rather than bland light blue screen

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#151]

**Comment by Gardenette** [comment]
What background did we want specifically? A background of what?

**Comment by stygmaskyzoo** [comment]
current background is this and looks awful
![introbg](https://user-images.githubusercontent.com/73248181/188614713-6c5b3e11-6761-48de-8f5f-2223ab78da21.png)

**Comment by Gardenette** [comment]
I changed it but it's still a placeholder
