### ISSUE TITLE
Ceiba's dialogue needs to be redone

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#154]
Lots of "and"s and commas
Take out Ceiba explaining the perfect IVs
Take out Ceiba stating which buttons do what
Intro is too long

**Comment by Gardenette** [comment]
All that's left on this one is the intro is kind long

**Comment by Reahn** [comment]
Hey guys, what else needs to be edited so far? Is there anything I can help with?

**Comment by stygmaskyzoo** [comment]
> Hey guys, what else needs to be edited so far? Is there anything I can help with?

i'm sorry, but who are you?

**Comment by BlueLightning8** [comment]
Done. opened new issue with doc link
