### ISSUE TITLE
Have books as collectables?

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#198]

**Comment by Gardenette** [comment]
Do we know if we are doing this?
If we are doing it, what's it for and how should I implement it?

**Comment by stygmaskyzoo** [comment]
i like this idea, i think we can either make something quick for demo and test it out or erase it for the moment and think in it later and try to implement it for demo 2

**Comment by KalojaGod** [comment]
Discussed during meeting:
Lore books in different shelves and buildings. You are only able to read it. Achivment consideration for reading all the books.
Encourage exploring looking for special lore books, maybe numbered volumes.

**Comment by Gardenette** [comment]
Will get to this after incorporating achievements

**Comment by Gardenette** [comment]
Suggested achievement in achievements channel
