### ISSUE TITLE
better ai

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#2]
the region is **mostly doubles** so we need a good ai for that

**Comment by Shadowsoftime99** [comment]
My current plan is to base this off of the Reborn/Rejuvenation AI. I asked and have gotten a confirmation that their AI script is available for public use. Probably going to require a lot of stripping out their field-effect specific logic, but it _is_ able to play doubles already

**Comment by Gardenette** [comment]
@LowEffortCoding did you ever incorporate that script for better ai in 20.1?

**Comment by LowEffortCoding** [comment]
did ye, the AI uses weather moves/hyper beam more, theoradically

**Comment by Gardenette** [comment]
Cool. Can we close this one then?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
