### ISSUE TITLE
If you go back to your house after choosing the starter, the dialogue between Ceiba and Mom restarts

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#202]

**Comment by Gardenette** [comment]
@Ketyna are you certain your sister had the latest of the project? Looking at the events I can't see a way this could have happened unless she warped to a different map at some point and basically went out of order

**Comment by Ketyna** [comment]
@Gardenette I'll ask my sister to update and retry, it might have been an older version

**Comment by Ketyna** [comment]
My suspicion is a trigger problem caused by an update that made it redo the scene after already having done the demo

**Comment by Gardenette** [comment]
Okay. Let me know if it persists after your sister pulls the latest and starts a new game
