### ISSUE TITLE
cerigold cemetery rework

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#216]
katie knows

**Comment by KalojaGod** [comment]
Instead of grass encounter make Flower encounters:

**Comment by KalojaGod** [comment]
Funny grave considiration: family recipe engraved on grave (happens irl) - Katie

**Comment by Ketyna** [comment]
Scrap skull layout, have more coordinated/logically placed graves and a clearer path. Flowerbed autotiles instead of Grass autotiles for encounters. More dense graves, more well-kept foliage, no more bushy mess.

Have Gym entrance guy(tm) at the front, so people know they've entered the gym.

**Comment by Ketyna** [comment]
Considering having several fenced off areas for different families, for easter eggs, or for different encounters. Maybe even some busted item idrk
