### ISSUE TITLE
big trees arent aligned in cerigold in relation to veravalles

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#221]

**Comment by Tydvs** [comment]
Is this still an issue? Can I get more info on this, I may be able to help if no one else is working on this

**Comment by Gardenette** [comment]
> Is this still an issue? Can I get more info on this, I may be able to help if no one else is working on this

@Ketyna @KalojaGod is this still an issue?

**Comment by KalojaGod** [comment]
Still an issue, Katie was on it but got caught up irl. I can tackle it soon(tm)

**Comment by Gardenette** [comment]
Tydvs was asking if they can work on it. Is this something they can do for us?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KalojaGod** [comment]
Hmm they can, its easy if you know how...Was thinking of using your script for this would be easier. Its just a lot of explaining.

But Tydvs is now on break and slowly coming back

**Comment by KalojaGod** [comment]
FINISHED B)
