### ISSUE TITLE
add move reminder and name rater to the pokecenter

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#277]

**Comment by Gardenette** [comment]
We are adding this to the pokecenter rather than the party?
If that's the case, I vote we have it doable via a machine rather than a guy

**Comment by Gardenette** [comment]
It could be paid for by the neo corporation or something and require money or a heart scale or something

**Comment by Gardenette** [comment]
In sv you can rename a pokemon from its summary screen, which is nice
You can relearn moves from there too

**Comment by stygmaskyzoo** [comment]
rename from the menu is great
move relearner from the menu is great if we limit it in some zones (you cant change moves in the middle of a gym or the e4)

**Comment by Gardenette** [comment]
Remember move:
If flag "lock move reminder" is not on map, will be available
