### ISSUE TITLE
Cerigold festival

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#288]
Need the following:
NPCs dancing
NPCs dressed for the event (dresses)
A band playing
Fog lighting
A crowd at the gym, watching Valentina battle

Dialogue for NPCs:
Imply that some people who are there are families that live in cerigold
Change Alma's conversation with Alma so she doesn't agree with Val, but she still lets her go. Maybe something like "I still hold fast to the belief our tradition is extremely important... but if my granddaughter is truly this unhappy..." "I will find someone else to take my place as gym leader." Or something like that.

**Comment by KalojaGod** [comment]
Still need:
-Overworld people dressed for the event when dancing.
-Band is too much effort for overworld and mapping (can be done, maybe)
-Gym have place for people watching, just have to be implemented.

**Comment by stygmaskyzoo** [comment]
i think current iteration is fine enough, can i close this?
