### ISSUE TITLE
Make pause menu less cluttered

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#313]

**Comment by Gardenette** [comment]
Find out what can be condensed into what

**Comment by Gardenette** [comment]
Working on phone idea to pull all of these features inside:
Pokedex
Trainer card
Map
Wiki
Objectives

**Comment by stygmaskyzoo** [comment]
that is a menu into a menu, not sure if that solves the problem

**Comment by ChespinCraft** [comment]
What about a hotkey then?

**Comment by Gardenette** [comment]
SV does map, trainer card, and pokedex in the same menu. You do get to it via hotkey to Chespin's point

**Comment by Gardenette** [comment]
Salt is working on phone UI

**Comment by Gardenette** [comment]
This is now in a new github issue
