### ISSUE TITLE
Add Pokevial and hotkey from party menu

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#314]

**Comment by Gardenette** [comment]
Added pokevial. Have not added hotkey to party menu yet

**Comment by Gardenette** [comment]
Waiting on an answer from FL on controls screen

**Comment by ChespinCraft** [comment]
This is finished right?

**Comment by Gardenette** [comment]
Yes courtesy of our new coder qin

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
