### ISSUE TITLE
Welcome to Mapping

### ISSUE THREAD

**Issue by KalojaGod** [untamed-team/project-untamed#322]
Need it before demo

**Comment by Gardenette** [comment]
@KalojaGod is this still needed? Anything I can help with?

**Comment by KalojaGod** [comment]
Still needed. Spork offered to help yesterday with tile-tileset tutorial. Sooooo i will most likely coordinate with Spork (when they feel better)

**Comment by Gardenette** [comment]
We could use some concept art that owoodfin created. We can even cycle through different images maybe. Just for the demo
