### ISSUE TITLE
Need New Title screen

### ISSUE THREAD

**Issue by KalojaGod** [untamed-team/project-untamed#323]
Also with the comment that we need help somewhere??? as a second titel or smt idk

**Comment by Tydvs** [comment]
Ancient mural of the legendaries from one of the subjectively videos? Maybe ask Jack about getting the file so it's high def for our purposes? Or someone could remake it

**Comment by Gardenette** [comment]
> Ancient mural of the legendaries from one of the subjectively videos? Maybe ask Jack about getting the file so it's high def for our purposes? Or someone could remake it

We actually have that currently. It's pretty long

**Comment by KalojaGod** [comment]
We have a wip Title screen that can work for the demo if its approved. After lot of concept art on the Title work on it slowed down

**Comment by Gardenette** [comment]
I think the cinatic we have now works for demo. We just need to
1. Make it clear you can skip it
2. Have a static screen for the PRESS START screen

**Comment by Gardenette** [comment]
For the start screen
We could use some concept art that owoodfin created. We can even cycle through different images maybe. Just for the demo

**Comment by ChespinCraft** [comment]
We have this
<img width="512" alt="Screenshot 2022-12-30 at 11 43 39 AM" src="https://user-images.githubusercontent.com/70040639/210093454-6e448a18-7e8a-4644-9799-119f81360dfe.png">

**Comment by Gardenette** [comment]
WHERE DID TGIS COME FROM

**Comment by ChespinCraft** [comment]
its the wip concept art kaloja was talking about above

**Comment by Gardenette** [comment]
Well can we put this in the game now for the demo?

**Comment by Gardenette** [comment]
Well can we put this in the game now for the demo?

**Comment by ChespinCraft** [comment]
yeah its been in the game for like 2 weeks lol

**Comment by Gardenette** [comment]
Oh pfft I always launch in Debug. Cool

**Comment by Gardenette** [comment]
It just needs music now

**Comment by Gardenette** [comment]
got a placeholder

**Comment by Nifdoowo** [comment]
Okay yes I was looking into this, both the logo and the background.

**Comment by Gardenette** [comment]
Confused. Isn't this done for the demo?

**Comment by ChespinCraft** [comment]
I made a new logo thats actually a sprite, just waiting on a background for it--spork said they had an idea

**Comment by Gardenette** [comment]
OK cool

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChespinCraft** [comment]
Placeholder that's good enough for the demo

**Comment by stygmaskyzoo** [comment]
good enough for now
