### ISSUE TITLE
Make NPC for Escape Rope

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#341]
Since escape rope is a key item
"Why do people never take their rope back after using it?"

**Comment by stygmaskyzoo** [comment]
i think this should happen where is related, not for demo but in the caves or something

**Comment by Gardenette** [comment]
I'll put this in the gold mine for demo 2. An NPC isn't necessary. Could be an item found by an NPC who mentions they lost their escape rope
