### ISSUE TITLE
Battlebacks are always set to indoor1_bg for some reason

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#350]

**Comment by Gardenette** [comment]
Make a short script that changes the battleback based on the encounter type

**Comment by stygmaskyzoo** [comment]
that supposedly already happens

if you set the encounters to water or cave it should change but with rod this happens (even if the enter the battle animation works right)

![image](https://user-images.githubusercontent.com/73248181/211014225-293430f9-84e4-43bf-9674-bc62f7220bfb.png)

**Comment by micahtmaclean** [comment]
Happy to pick this up, but I'll need more direction. What conditions should have what backgrounds?

**Comment by Gardenette** [comment]
I will get a list when I can

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
