### ISSUE TITLE
Battle exp bar is flat

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#353]
Demo feedback:
the exp bar doesn't quite feel finished. I think it's design in how it curls at the end, and the way it sits under the health display are nice, but it feels very flat compared to the rest of the battle UI. Perhaps a second tone to the blue of the exp bar, to give it a bit of depth, would fix this.

**Comment by stygmaskyzoo** [comment]
the big issue is not the flat part, but it feels like its turned around, the curl at the end should be the last part and not the first, it also feels strange that the exp dont curl with it

**Comment by KalojaGod** [comment]
Remake pwease someone. Exp bar is not up to date

**Comment by Gardenette** [comment]
This is now in the github issue UI Needs
