### ISSUE TITLE
Cemetery tombstone text

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#355]
Demo feedback:
I think the cemetery's design is nice, with it's branches, but it feels a bit empty when most of them lead to nothing but tombstones without any dialogue. At the very least, including text on the tombstones could make this feel less empty, not like you have to add a bunch of items to find or anything

**Comment by stygmaskyzoo** [comment]
i'll close text because i'll fix this when addressing the flavor text issue
