### ISSUE TITLE
Mega post for gameplay changes from vanilla we have to discuss

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#361]
please comment with other stuff i forgot

- Changed iv's to not affect combat :heavy_check_mark:
- Dinamic ev's :heavy_check_mark:
- Some mons and moves have been slightly rebalanced :heavy_check_mark:
- Rebalance the type chart (bug super effective against fairy) :question:
- Add new typings to old mons :question:
- PC, Move Relearner and Renamer accesible from menu :heavy_check_mark:
- Evolve happens in party menu :heavy_check_mark:
- Make some held items like Focus sash infinite :question:

**Comment by LowEffortCoding** [comment]
the EV CAP of 510 isn't 510 at level 1, it was changed to be more dynamic
the maximum EVs a pokemon can have at a given time is directly correlated to the pokemon's level, the EV CAP gains 5~ EVs per level, and 6 every other level, so a pokemon at level 1 the EV CAP is 7, but when the pokemon has leveled up to level 10 the EV CAP is 61
currently, if max level is 100 and the EV CAP is 510, the pokemon has the maximum amount of EVs at level 90

**Comment by stygmaskyzoo** [comment]
you obain ev the vainilla way?

**Comment by LowEffortCoding** [comment]
by beating random shit, yes

**Comment by ChespinCraft** [comment]
Is focus sash/other items being infinite implemented? first I'm hearing of it

**Comment by LowEffortCoding** [comment]
its easy to add and its great QoL, just need to ensure you drop off focus sash at the right time 
but i can see why this shouldnt be added
