### ISSUE TITLE
add pokemon types in battle ui

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#362]
![types](https://user-images.githubusercontent.com/73248181/211206974-24031b89-5b6b-4643-a428-d03633074928.png)

to be similar to this:

![image](https://user-images.githubusercontent.com/73248181/211206995-ce076c1d-ad5f-4cea-807d-0a03e560f4d1.png)

**Comment by Gardenette** [comment]
This is taken care of with the addition of the battle info script
