### ISSUE TITLE
Credit: Low can be added to wiki section.  I think some people are missing and ask Kaloja what people need to be added from the tilesets she stole from

### ISSUE THREAD

**Issue by KalojaGod** [untamed-team/project-untamed#370]

**Comment by stygmaskyzoo** [comment]
that reminds me we have to credit all the random people from internet assets and i dont know if we are keeping track of that anymore

**Comment by KalojaGod** [comment]
Interier I took from drive Credit for outdoor: 
Tinytrashing
Aveontrainer
PokemonEclipse
PrincessPhoenix
Seiyouh
BE_Infinity
Magiscarf

**Comment by KalojaGod** [comment]
I dont know the old ones that other people took, But I have a list of the ones I took

**Comment by Gardenette** [comment]
Low is added. Let me know when your list of people to add is complete
