### ISSUE TITLE
two difficulties -> three difficulties 

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#371]
vainilla
rebalanced
hell

**Comment by LowEffortCoding** [comment]
can casual and normal use the same teams I have chronical laziness

**Comment by stygmaskyzoo** [comment]
yeah i dont really care, those 2 difficulties should be the same except for vanilla mechanics changes

**Comment by KalojaGod** [comment]
Discussed in meeting:
-Rebalanced Normal
-Rebalanced Hard (Rebalanced and hard)

We dont want Easy/Vanilla mode. There is just a small number of people that want easy mode. 

Dynamic mode discussion: No
