### ISSUE TITLE
Eventing tutorial 

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#379]
Add tutorial on player Pronouns in dialogue

**Comment by Gardenette** [comment]
Add map transfer quirks

**Comment by Gardenette** [comment]
On hold for now. We don't know for sure if we are getting rifld of map transfers

**Comment by Gardenette** [comment]
Requires a meeting discussion

**Comment by stygmaskyzoo** [comment]
i don't seem to understand what this is for
