### ISSUE TITLE
consider rick roll (?)

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#394]
i dont know

**Comment by Gardenette** [comment]
Yeah I can take out the browser thing. But I don't see a reason to get rid of the text on the grave

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: stygma ***@***.***>
Sent: Friday, January 27, 2023 11:27:19 AM
To: untamed-team/project-untamed ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [untamed-team/project-untamed] consider rick roll (?) (Issue #394)


i dont know

**Comment by stygmaskyzoo** [comment]
you can leave it or get rid of it
do what you want, it's your child, i think it's fun but i also understand why it could scare people (still think wiki must stay)
but close the issue when you are done xd

**Comment by Gardenette** [comment]
We'll see how it's received by Jack and his stream

**Comment by stygmaskyzoo** [comment]
well received by jack so i think it can stay for the moment
