### ISSUE TITLE
abilities and moves which flavor is bigger than the box

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#398]
(we should keep track of new ones in the future and take that into account when making flavor)

**abilities:**
fervor
blademaster
flare boost
toxic boost
moody

**moves:**
steam burst
pepper spray
scatterdust
scouring winds
psycrush
psysonic
slime shot

**Comment by ChespinCraft** [comment]
can yall check if the abilities are short enough now?

**Comment by LowEffortCoding** [comment]
toxic boost no
flare boost yes
moody no
blademaster yes
fervor yes

**Comment by ChespinCraft** [comment]
now?

**Comment by LowEffortCoding** [comment]
moody is good now, toxic boost still gets cut off

**Comment by ChespinCraft** [comment]
toxic boost is the same length as flare boost in PBS grief

**Comment by LowEffortCoding** [comment]
its not about character length its about the 'graphical text' length xd

**Comment by ChespinCraft** [comment]
can i see what it looks like rn

**Comment by LowEffortCoding** [comment]
all abilities now fit in the tiny desc box

**Comment by Gardenette** [comment]
We have a button you can press to view an ability desc now
