### ISSUE TITLE
dinamic difficulty is confusing for people

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#428]

**Comment by Gardenette** [comment]
There is no dynamic difficulty at this time. What do you mean?

**Comment by stygmaskyzoo** [comment]
> There is no dynamic difficulty at this time. What do you mean?

there is

low made it, independently of your difficulty settings the game adapts difficulty regarding how much time you need to kill the trainers or whatever

**Comment by Gardenette** [comment]
That's been disabled until it can be improved

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stygmaskyzoo** [comment]
great
