### ISSUE TITLE
cropmaster front is weird

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#430]
in objectives screen

**Comment by Gardenette** [comment]
How is the font weird?

**Comment by stygmaskyzoo** [comment]
**front**

as in front/back sprites

not font xd

**Comment by stygmaskyzoo** [comment]
the front in the quests should be this one
![image](https://github.com/untamed-team/project-untamed/assets/73248181/9ac5c8c2-2b9a-4000-b507-86ab50ff5dfb)
