### ISSUE TITLE
Trainer Tips

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#434]
- [x] Like the objectives log, but it shows the tutorial tips you have seen before, and you can view them at any time after unlocking them
- [x] Update tutorial for multisave now that there are arrows on the continue screen and now that the save screen looks different
- [x] Create tutorial for checking battle stats (m and n buttons)
- [x] Later on, edit tipBattleInfoCont so it shows info about different icons and their meanings
- [x] Updated advanced dex tutorial to show you how to use the dex search functions
- [x] Proper tips for cooking

**Comment by Gardenette** [comment]
Update tutorial for multi save once the continue screen has arrows for selecting save slot

**Comment by stygmaskyzoo** [comment]
pokevial tutorial triggers if you open summary menu after rival battle but before actually obtaining pokevial

**Comment by Gardenette** [comment]
For battle info icons, I asked Low what some of them mean so I know how to describe them if I need to describe them.

when "Contact"             then idx = 4
      when "TramplesMinimize"    then idx = 5
      when "HighCriticalHitRate" then idx = 6
      when "ThawsUser"           then idx = 7
      when "Sound"               then idx = 8
      when "Punching"            then idx = 9
      when "Biting"              then idx = 10
      when "Bomb"                then idx = 11
      when "Pulse"               then idx = 12
      when "Powder"              then idx = 13
      when "Dance"               then idx = 14
      when "Slicing"             then idx = 15
      when "Wind"                then idx = 16
      
![move_icons](https://github.com/untamed-team/project-untamed/assets/106409863/188cdb67-b23a-451c-93fd-fa320c4d9408)

**Comment by Gardenette** [comment]
List of what's needed for the tip:
So the ones I do need to show and give a brief desc of are:
Contact
Tramples mini
Sound
Punching
Biting
Bomb
Pulse
Powder
Dance

And we aren't using the rest?
