### ISSUE TITLE
create a way to make 2 requirement evolution methods

### ISSUE THREAD

**Issue by LowEffortCoding** [untamed-team/project-untamed#436]
make so specific evo methods can have two different "parameters"

**Comment by Gardenette** [comment]
Like
evolve if THIS or THAT
or
evolve if THIS and THAT

**Comment by LowEffortCoding** [comment]
this AND that
this OR that is piss easy

**Comment by Gardenette** [comment]
I don't understand why you don't use && though

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LowEffortCoding** [comment]
oh I already did that, ItemLevel35 uses &&
in my dream scenario you get to set what item you want and what level you want, having 2 different variables for evolutions basically

**Comment by Gardenette** [comment]
What is the mon and what are the conditions

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LowEffortCoding** [comment]
the corn currently uses ItemLevel35 for both blazea and maymaz, blazea uses fire stone while maymaz uses the sun stone
the level 35 requirement is fixed as you can imagine by the naming

**Comment by Gardenette** [comment]
So it doesn't allow for over level 35?

**Comment by Gardenette** [comment]
Seems like it does. I'm confused

**Comment by LowEffortCoding** [comment]
if I want to let's say, make a mon evolve with a item and above or equal level 40
I would need to make a "new" evolution method, as I can't input 2 variables for the evolution

**Comment by Gardenette** [comment]
Oh I gotcha

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Gardenette** [comment]
I was gonna try to figure it out
But if FL says it's a lost cause without changing how the compiler works, I believe him
https://www.pokecommunity.com/showthread.php?t=338872

**Comment by Gardenette** [comment]
Maruno also says on the wiki that you only have one parameter to work with unfortunately

**Comment by LowEffortCoding** [comment]
aw man :(
guess I will do the way it is currently then, thanks for the help though
