### ISSUE TITLE
make hm's interesting

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#437]

**Comment by LowEffortCoding** [comment]
what does this mean? they are very useful tools for rewarding backtracking and exploration 
the only issues i had with HMs is that they were permanent and useless in battle; which now are both fixed, pretty sure item HM replacements are going to be a thing mid-late game depending of the HM as well

**Comment by stygmaskyzoo** [comment]
> what does this mean? they are very useful tools for rewarding backtracking and exploration the only issues i had with HMs is that they were permanent and useless in battle; which now are both fixed, pretty sure item HM replacements are going to be a thing mid-late game depending of the HM as well

if those are fixed 
good enough
