### ISSUE TITLE
THE "JACK PLS FIX" LIST (from the dex dept)

### ISSUE THREAD

**Issue by LowEffortCoding** [untamed-team/project-untamed#443]
[this was made with the intent of just copypasting into jack's DMs, but very few have said power]

this is a list of various tweaks, ranging from slight type alterations to full new forms, these are politely asked to be addressed, do not feel in any way obligated to do any of these, this is purely from a gameplay POV.

__*high priority:*__
> flying mega evolution 
from our rules of blocking overly popular pokemon and avoiding broken pokemon while also giving a mega for each type, we kinda met a stone wall in this one. we wont have salamence, rayquaza, aerodactly or charizard as they are overly represented or flat out broken, the only flying mega evolution that doesnt break any of our guidelines is mega pidgeot; which is a gen1 pokemon not many are found of. some of us thought of a mega noivern or mega delibird, but not much else.
--------------------
> grass/dragon titantrops
this one felt under the radar when we were doing the type balancing questions, as everyone thought he was a grass/dragon from the beginning, and for that low personally apologises. This change is mostly because pure grass can see as a downgrade, titantrops aura is also very intimidating,.

__*low priority:*__
> sand form for castform
castform not having a sandstorm variant always felt like a strange case, hes whole identity is that he adapt to all weathers, so why doesnt he have a rock form? it is overwall a mistake in need of fixing.
--------------------
> more custom megas
this point is very general, as it should, the whole stick of the game is mega evolution, for example other games add up to 20 new megas! its fine for us to reuse old entries, but newer ones given to forgotten pokemon will always be nice

more cases of Mega Mawile are needed, instead of the unfortunate Mega Rayquaza cases we have been given over the years, but im sure you understand this last point as a good portion of your megas have been given out to mediocre pokemon, and for that im greatful c:

__*just suggestions:*__
> more trims for furfrou
we are adding the cool little but forgotten doggo from gen6 as is, it has already lots of banger designs but some of the main devs thought it would be a nice addition to give him some new hairstyles. not needed in any way tho.

**Comment by stygmaskyzoo** [comment]
i sent this to jack yesterday
no answer still, can't promise he will answer

that said i think if he intends to stop doing mazian videos for now we can start thinking (probably _after_ demo 2) about what custom things we want (new megas, etc.) and ask for permission to just make them ourselves

**Comment by stygmaskyzoo** [comment]
since we already got jack's answer closing this
