### ISSUE TITLE
Cerigold time lock changes 

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#451]
https://discord.com/channels/@me/983053380605861889/1074712733611724951

**Comment by Gardenette** [comment]
"In light of recent feedback, I think it would be best if the festival in cerigold lasted several days canonically so we don't lock time when the festival starts
And instead of it automatically starting when you get there at night, you could do something to trigger it. Maybe complete a little quest to help finish preparations for it?"

**Comment by Gardenette** [comment]
In light of recent feedback, I think it would be best if the festival in cerigold lasted several days canonically so we don't lock time when the festival starts
And instead of it automatically starting when you get there at night, you could do something to trigger it. Maybe complete a little quest to help finish preparations for it?

**Comment by stygmaskyzoo** [comment]
so now it triggers when at night or when you do the dialogue with alma and val? i think it's better if it triggers after val and alma cutscene

**Comment by Gardenette** [comment]
It triggers after Val and Alma cutscene in cemetery
@BlueLightning8
Did you ever settle on how we can notify the player that talking to väl and Alma will progress the festival?

**Comment by BlueLightning8** [comment]
I think just a warning screen saying that entering will progress the story like they often do in AAA games is the simplest cleanest solution
