### ISSUE TITLE
gifted pokemon wont listen

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#453]
https://discord.com/channels/969006224039370794/1075177470837391402/1075177470837391402

**Comment by LowEffortCoding** [comment]
this is intentional, pokemon with different OTs dont listen if your badge count are low
sign of respect or something?

**Comment by Gardenette** [comment]
We don't want this to happen with floette tho do we?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Gardenette** [comment]
@LowEffortCoding We don't want this to happen with floette tho do we?
Maybe change floette's level to 10 or something
Won't be an issue with zolupine in the near future since zolupine won't be a gift pokemon in the next demo/full game

**Comment by LowEffortCoding** [comment]
I don't think it's a issue for either really, next demo is level 20-30 right?

**Comment by Gardenette** [comment]
At least

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
