### ISSUE TITLE
fix backsprites in pokedex

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#467]

**Comment by Gardenette** [comment]
@KalojaGod  how did you get it 300% like this?

**Comment by ChespinCraft** [comment]
(its my ss lol) by manually importing and re-exporting the sprites in a program online

**Comment by Gardenette** [comment]
Interesting. I don't see double pixels so however you did it worked. Could you do that for them all and / or possibly write the process down and give to spork/art dept?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChespinCraft** [comment]
yeh I'm planning on it, just really tedious so ive been putting it off lol

**Comment by Gardenette** [comment]
Fair. If you wrote down the process, spork can give it to someone in the art dept as grunt work

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stygmaskyzoo** [comment]
tbh this post is for the backsprites getting out of the box in the dex tab, not for the battle backsprites xd

**Comment by Gardenette** [comment]
Oh so they just need to be moved up in the dex box?
