### ISSUE TITLE
add the npc that indicates you are in a gym in graveyard

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#496]
the one in every gym in pokemon

**Comment by stygmaskyzoo** [comment]
it is a placeholder now

**Comment by stygmaskyzoo** [comment]
this guy probably needs a dialogue that says "wow you can even capture mons in the gym!"

**Comment by Gardenette** [comment]
I was thinking more like having one of these guys
https://gamefaqs.gamespot.com/boards/960099-pokemon-heartgold-version/49444914

But I'm down for whatever
