### ISSUE TITLE
molucotta sucks at the beginning 

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#498]
and quetza is the best

at least people say this

**Comment by stygmaskyzoo** [comment]
https://discord.com/channels/969006224039370794/1075081255193956453/1075081255193956453

this person has a point

**Comment by LowEffortCoding** [comment]
i will be honest with you thats just grass starters in a nutshell

**Comment by stygmaskyzoo** [comment]
> i will be honest with you thats just grass starters in a nutshell

https://discord.com/channels/969006224039370794/1075081255193956453/1076737641787179069

**Comment by Gardenette** [comment]
There is an ongoing discussion about this in cha ge proposals in the main server

**Comment by stygmaskyzoo** [comment]
closed until we take a look at demo 2 feedback
