### ISSUE TITLE
mom recharging pokevial

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#499]

**Comment by Gardenette** [comment]
Do we need this? Canonically I can't think of a way for the mom to do it since the vial uses pokecenter healing technology or something

**Comment by stygmaskyzoo** [comment]
it has to do with the fact that you obtain pokevial at the beginning of demo 1 but then dont have access to the center in the entirety of the demo

**Comment by stygmaskyzoo** [comment]
ok not needed since hacienda has healing spots now
