### ISSUE TITLE
Following pokemon sometimes cut off inside player

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#506]
https://discord.com/channels/969006224039370794/1078731092833620141/1078742462379606016

**Comment by stygmaskyzoo** [comment]
is this still a thing?
i remember your push fixing it (?)

**Comment by Gardenette** [comment]
It's still a thing. I think the fix would be to have the following pokemon cover the player instead of the player cover the follower, but not sure how to do that. Haven't looked into it yet

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stygmaskyzoo** [comment]
i don't think this can be fixed tbh except slightly moving the sprites of the specific mons that clip

**Comment by stygmaskyzoo** [comment]
not major thing, i think we can forget it for the moment
