### ISSUE TITLE
Move battle info tutorial to after rival battle

### ISSUE THREAD

**Issue by ChespinCraft** [untamed-team/project-untamed#555]
Maybe put it in first wild battle or first rt 1 trainer battle

**Comment by Gardenette** [comment]
Note to self: use story progression variable as part of condition

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: ChespinCraft ***@***.***>
Sent: Saturday, March 11, 2023 12:11:56 PM
To: untamed-team/project-untamed ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [untamed-team/project-untamed] Move battle info tutorial to after rival battle (Issue #555)


Maybe put it in first wild battle or first rt 1 trainer battle
