### ISSUE TITLE
inbattle tip doesnt show what keys need to be pressed

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#598]

**Comment by Gardenette** [comment]
@stygmaskyzoo  for some reason some of the code was commented out. Can you download the latest and try again please?

**Comment by micahtmaclean** [comment]
I ran into this issue as well. With the current version of the code, if you don't have the options "Battle Info" and "Move Info" in your control settings you can reset to the default controls to add them.

**Comment by micahtmaclean** [comment]
Can someone close this issue? This issue was solved when I started doing work. @Gardenette @stygmaskyzoo
