### ISSUE TITLE
Demo Save Data Incompatible  

### ISSUE THREAD

**Issue by micahtmaclean** [untamed-team/project-untamed#616]
The demo save data seems to store quests differently causing errors and is missing the controls "Battle Info" and "Move Info".

**Comment by Gardenette** [comment]
In what way does it seem to store quests differently compared to the demo?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Micah ***@***.***>
Sent: Saturday, April 1, 2023 5:41:17 PM
To: untamed-team/project-untamed ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [untamed-team/project-untamed] Demo Save Data Incompatible (Issue #616)


The demo save data seems to store quests differently causing errors and is missing the controls "Battle Info" and "Move Info".

**Comment by Gardenette** [comment]
Also the demo dlsave data will not carry over to the next demo so this is not an issue

**Comment by micahtmaclean** [comment]
I'm not sure exactly, but for some reason I got errors with the quests on my demo save file. Glad this is a non-issue.
