### ISSUE TITLE
Needed Hungry Emote for Camping

### ISSUE THREAD

**Issue by micahtmaclean** [untamed-team/project-untamed#628]
I need someone to create an emote to show when pokemon are hungry during camping

**Comment by ChespinCraft** [comment]
Do you know where in the game files those are? i want to base it off the existing ones + i need the sizing ref

**Comment by Gardenette** [comment]
Graphics
Animations
Follower emotes

**Comment by KalojaGod** [comment]
![emo2](https://user-images.githubusercontent.com/111147582/230715761-fac0c0e9-9475-4867-89ca-9da539daf808.png)
![emo](https://user-images.githubusercontent.com/111147582/230715764-0c29b4ee-e2ac-4856-b89d-abcf47b3dc74.png)
