### ISSUE TITLE
add saltilton's backgrounds

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#632]
https://drive.google.com/drive/folders/1TARB3r3-s-B_H6-W_fG1pAALZXBqNfmZ?usp=sharing

**Comment by KalojaGod** [comment]
Where did they get these??

**Comment by stygmaskyzoo** [comment]
are this correctly showing in battle

they are supposedly free use

**Comment by KalojaGod** [comment]
opps, I just put them in the files
