### ISSUE TITLE
Implement new battlebacks

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#668]
https://drive.google.com/drive/folders/1TARB3r3-s-B_H6-W_fG1pAALZXBqNfmZ?usp=sharing

**Comment by LowEffortCoding** [comment]
woah, they are really pretty

**Comment by ChespinCraft** [comment]
I thought some of these were already added?

**Comment by Gardenette** [comment]
Idk

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChespinCraft** [comment]
I checked, theyre already in the files

**Comment by Gardenette** [comment]
Cool nvm then

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stygmaskyzoo** [comment]
added
