### ISSUE TITLE
Change detailed damage information to Debug mode only

### ISSUE THREAD

**Issue by ChespinCraft** [untamed-team/project-untamed#683]
![image](https://github.com/untamed-team/project-untamed/assets/70040639/44afc983-8461-482b-8c8b-fbaa24f65e1c)

**Comment by LowEffortCoding** [comment]
[f6, iirc, turns this on and off]

**Comment by ChespinCraft** [comment]
it should only be toggleable for debug mode tho

**Comment by LowEffortCoding** [comment]
why?

**Comment by ChespinCraft** [comment]
<img width="621" alt="Screenshot 2023-06-23 at 9 02 31 PM" src="https://github.com/untamed-team/project-untamed/assets/70040639/8f0d71db-4a5d-4373-9720-2f06e46b9092">

**Comment by LowEffortCoding** [comment]
e
sure then
