### ISSUE TITLE
Evasion move reworks and Endure

### ISSUE THREAD

**Issue by ChespinCraft** [untamed-team/project-untamed#684]
-make double team +1 speed +1 accuracy
-make minimize +1 speed +2 accuracy
-remove evasion from the acupressure table
-remove endure from universal TM list

**Comment by LowEffortCoding** [comment]
I think evasion is already excluded from the Accu table

**Comment by ChespinCraft** [comment]
Removed endure from the universal TM list, I just checked and evasion is not excluded from acupressure.

**Comment by LowEffortCoding** [comment]
https://github.com/untamed-team/project-untamed/commit/a1d2eb126e0c2dc0e94fa60184f6c6660a901e58

**Comment by ChespinCraft** [comment]
https://github.com/untamed-team/project-untamed/commit/e62572114683387730be0af5c3453d32ced3d724#diff-a740b69c2dc5d04649fccc9c4e99a4c67156e59f76f93507423b45fa04945cc8
