### ISSUE TITLE
lacking ui

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#70]
-wip-

**Comment by Gardenette** [comment]
What cancel button doubles? Can you get a screenshot?
Pokegear was taken out so that's not an issue anymore

**Comment by stygmaskyzoo** [comment]
cancel button is already done,
the list is more or less #art-to-do-list
but only saltinton has been making ui lately

**Comment by stygmaskyzoo** [comment]
we're pretty close to complete all the ui, im closing this anyway because i never added the to-do-list here
