### ISSUE TITLE
Map should show where you are

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#761]
Specially in map menu bur probably also a good idea if it does it when you look at a map in the world

**Comment by Gardenette** [comment]
https://reliccastle.com/resources/1404/

**Comment by Gardenette** [comment]
Need to finish townmap.txt pbs file

**Comment by stygmaskyzoo** [comment]
![image](https://github.com/untamed-team/project-untamed/assets/73248181/33a9f803-96aa-49ee-b258-d99d51d2f2df)

still not working

**Comment by Gardenette** [comment]
Where on the map are you standing? In Veravalles?
I assume you're inside because I just realized that's a problem
