### ISSUE TITLE
Hacienda Castaneda Corn Encounters Not Functioning Properly

### ISSUE THREAD

**Issue by ChespinCraft** [untamed-team/project-untamed#794]
Mazian Ekans and Pumpkaboo, and Pacuna and Wrenner can be found, which makes it seem like its using both the encounter tables for the Hacienda Fields corn and the Hacienda Castaneda land.

**Comment by ChespinCraft** [comment]
When you encounter a mazian ekans in this corn, they can be found with their hidden ability for some reason
<img width="514" alt="Screenshot 2023-12-09 at 3 57 34 PM" src="https://github.com/untamed-team/project-untamed/assets/70040639/68a22d45-39d2-473c-9f25-cb0915808a30">

**Comment by LowEffortCoding** [comment]
can you try to catch multiple ones

**Comment by LowEffortCoding** [comment]
or see if they learn SNARL at level 12

**Comment by ChespinCraft** [comment]
It did learn snarl
So its coming from pokemon_2.txt?

**Comment by ChespinCraft** [comment]
Also not sure if this is related or just luck but i found a shiny one 🫣

**Comment by ChespinCraft** [comment]
zea-zaya also dont appear to be showing up btw

**Comment by LowEffortCoding** [comment]
Intentional. Did you ever have variable 101 higher than or equal to 2?

**Comment by ChespinCraft** [comment]
How would I check that

**Comment by LowEffortCoding** [comment]
F9 -> Field -> Variables -> Scroll down

**Comment by ChespinCraft** [comment]
Its at 0

**Comment by LowEffortCoding** [comment]
weird, weird, very weird. Try reinstalling?

**Comment by ChespinCraft** [comment]
Ok i did and the encounters are still not correct, but i dont seem to be getting ekans with intimidate anymore, and theyre learning glare at lvl 12 so it seem the pokemon_2.txt issue is fixed

**Comment by Gardenette** [comment]
@ChespinCraft  good to close this?

**Comment by ChespinCraft** [comment]
@Gardenette still not working properly-- found techuppi in the hacienda corn when this is the supposed encounter list
<img width="127" alt="Screenshot 2024-03-26 at 12 23 56 PM" src="https://github.com/untamed-team/project-untamed/assets/70040639/43ebb19c-e5ff-4459-b73d-ebc31f64fba1">

**Comment by ChespinCraft** [comment]
Garden and low....its broken again. Tested and still getting m ekans and techuppi in hacienda castaneda corn

**Comment by Gardenette** [comment]
Fixed it by making the corn tiles the terrain tag number 18 rather than 2 that some of them were set to. 2 is regular grass
