### ISSUE TITLE
Fishing is broken

### ISSUE THREAD

**Issue by ChespinCraft** [untamed-team/project-untamed#795]
<img width="508" alt="Screenshot 2023-12-09 at 3 46 07 PM" src="https://github.com/untamed-team/project-untamed/assets/70040639/b703c8b9-6e20-451d-9f51-3be7bc245749">
<img width="509" alt="Screenshot 2023-12-09 at 3 46 16 PM" src="https://github.com/untamed-team/project-untamed/assets/70040639/b4684526-c5ab-4ae9-b030-29e63ebed512">

**Comment by Gardenette** [comment]
Which rod were you using? Old?

**Comment by ChespinCraft** [comment]
Yes
