### ISSUE TITLE
Terreon (BACK)

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#830]
Front is done, back needs to be redone

![Image](https://github.com/untamed-team/project-untamed/assets/106409863/3d8b50a2-23df-40b8-8254-c9813b309dec)
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/07155edb-de16-47e3-849e-0695096307fa)
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/617dced0-e1c0-49fe-8ae7-c631a3b74f61)
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/45e6b460-6f9c-4d05-940a-81213332d1c9)

**Comment by K-energy22** [comment]
K-Energy is working on it

**Comment by ChespinCraft** [comment]
![Image](https://github.com/user-attachments/assets/fa42a103-d28a-478e-bfbd-3ac5f241b4c2)
![Image](https://github.com/user-attachments/assets/a7b5edbc-6907-429e-82a3-d335754fb8a6)
