### ISSUE TITLE
music tracks needed

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#84]
- title screen
- gym leader
- start menu
- eon grunt battle
- eon cutscenes
- wild battle
- graveyard trainer notice (?)

**Comment by Gardenette** [comment]
I will make a checklist for Star!!

**Comment by Gardenette** [comment]
Again, it's fine to have placeholders. Just need to know which tracks go where. Guide me please :)
Title screen
Load screen
Intro with Ceiba
Veravalles
Ceiba's lab
Wild battle
Route 1
Eon grunt encounter (like when you find them and see cutscenes with them)
Eon grunt battle theme
San Cerigold town (not during festival)
San Cerigold town during the festival
San Cerigold graveyard (find something gym-esque but not too upbeat)
Valentina gym fight music
Hacienda castaneda (farmy/ranchy)

Will let you know if more are needed!

**Comment by LowEffortCoding** [comment]
closed for now
