### ISSUE TITLE
Zarcoil (BACK)

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#841]
front done, back needed

![Image](https://github.com/untamed-team/project-untamed/assets/106409863/b0ef7d8e-ce4d-4431-9858-2b64e0986afd)
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/4732c7b6-997b-430f-b2d1-9658ba1d3681)
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/5e4ccb4d-d7a9-4f2a-a62c-26ee3c3409a2)

**Comment by K-energy22** [comment]
K-energy22 is working on it

**Comment by ChespinCraft** [comment]
![Image](https://github.com/user-attachments/assets/6c971b4d-a5de-4046-9368-9bf2bebb5266)
![Image](https://github.com/user-attachments/assets/f85e1930-2eb0-43cb-894a-9fb79189a309)
![Image](https://github.com/user-attachments/assets/9a04cf45-cd1a-4b2f-a55d-02b0fe118099)
![Image](https://github.com/user-attachments/assets/64bdf80a-0733-4f8e-b19f-67326a847238)
![Image](https://github.com/user-attachments/assets/79f4e770-6133-4b2d-95e5-0884d0260ec5)
![Image](https://github.com/user-attachments/assets/18816793-6af5-4146-8ed9-c68d2006e265)
