### ISSUE TITLE
contests gimmick

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#87]
jack wanted it

**Comment by Gardenette** [comment]
https://www.pokecommunity.com/showthread.php?t=332168&page=5

**Comment by Gardenette** [comment]
Will get to this after camp

**Comment by Gardenette** [comment]
![dressing up](https://user-images.githubusercontent.com/106409863/229375466-3ef9880d-502b-48cf-80ae-a39807cd198e.PNG)

**Comment by Gardenette** [comment]
https://www.youtube.com/watch?v=pSFNfm2ycJQ

The hearts appear instead of the circles when an accessory is used
![dressing up1](https://user-images.githubusercontent.com/106409863/229375532-944220bb-d785-4d29-aaf6-1f2c423f8160.PNG)

**Comment by Gardenette** [comment]
![change bg during dress up](https://user-images.githubusercontent.com/106409863/229375590-be928f92-3e75-4616-9c50-a0d94c282852.PNG)
