### ISSUE TITLE
map crashes, probably a old tip leftovers

### ISSUE THREAD

**Issue by LowEffortCoding** [untamed-team/project-untamed#876]
https://discord.com/channels/1077656889665536030/1077939275728949379/1221406615736025128

**Comment by Gardenette** [comment]
This likely is not caused by a left over tip unfortunately. I'll have to do some digging.
I think it's caused by an outdated version of the region map plugin we're using.
Happens only when launching map from pokedex entry (pokemon's location)

**Comment by Gardenette** [comment]
![image](https://github.com/untamed-team/project-untamed/assets/106409863/85ec9c7c-2afd-4ac3-a9f6-31a9e34d6ce7)

**Comment by Gardenette** [comment]
Nope. Found it quickly. It was totally from a leftover tip.
