### ISSUE TITLE
Venorayge

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#888]
Front is done, back is needed

![Image](https://github.com/untamed-team/project-untamed/assets/106409863/3ef959ec-999f-4a48-976d-d3aba2b2e347)
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/ef5798bf-cdc1-429e-b924-9e051de890f8)

**Comment by ChespinCraft** [comment]
![Image](https://github.com/untamed-team/project-untamed/assets/70040639/bc1630a6-4faf-445d-8037-5dc995a90702)
![Image](https://github.com/untamed-team/project-untamed/assets/70040639/de5b79c9-6849-43b7-a2b8-a35a86112120)
