### ISSUE TITLE
custom intro and menu screen

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#9]

**Comment by stygmaskyzoo** [comment]
added modular title screen, need custom stuff

**Comment by stygmaskyzoo** [comment]
as far as we know, there is no support default for movies in essentials, there is an outdated script that can run flash movies

**Comment by Gardenette** [comment]
Currently waiting in an official intro from MillerMiller

**Comment by stygmaskyzoo** [comment]
current intro is a placeholder right?

**Comment by Gardenette** [comment]
Correct

**Comment by stygmaskyzoo** [comment]
good enough for now
