### ISSUE TITLE
Rustache

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#971]
![Image](https://github.com/untamed-team/project-untamed/assets/106409863/b1b6fa2a-b376-43ae-bb03-b66dfcc5e010)

**Comment by CeleryGuy** [comment]
Working on it

**Comment by CeleryGuy** [comment]
![Image](https://github.com/untamed-team/project-untamed/assets/167336056/066077cf-140d-4168-94cd-c1a9227d10cc)



![Image](https://github.com/untamed-team/project-untamed/assets/167336056/88348ca5-c964-4b1f-bbd5-ce21b1603c98)

**Comment by ChespinCraft** [comment]
![Image](https://github.com/untamed-team/project-untamed/assets/70040639/6fccb397-0b3a-489f-84a1-d99d7e209ccc)
![Image](https://github.com/untamed-team/project-untamed/assets/70040639/c020d5d8-46c2-4c97-b6a1-5bf8825c382d)
