### ISSUE TITLE
voltsy menu exploding after saving

### ISSUE THREAD

**Issue by LowEffortCoding** [untamed-team/project-untamed#975]
https://discord.com/channels/1077656889665536030/1077939275728949379/1221531722617983006
https://discord.com/channels/1077656889665536030/1077939275728949379/1221282060774412370

**Comment by Gardenette** [comment]
Asked Low if he located the cause of this
I've fiddled with it a good bit but it seems the issue persisted last I left it

**Comment by Gardenette** [comment]
Low thinks he fixed it. We'll see if it pops back up
